trigger: none

pool:
  vmImage: ubuntu-latest

resources:
  pipelines:
    - pipeline: DevArtifact
      source: "Build & Deploy to Dev"

variables:
  - template: templates/vars-global.yml

stages:
  - stage: deploy_to_test
    displayName: deploy to test
    variables:
      - group: "Test"
    jobs:
      - job: Deploy
        displayName: "Deploy"
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - download: DevArtifact
            artifact: drop

          - template: templates/deploy.yml
            parameters:
              path: $(Pipeline.Workspace)/DevArtifact/drop

      - job: DbUp
        dependsOn: Deploy
        steps:
          - template: templates/dbup.yml
